#! /bin/sh
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Tomcat
# Description: This file starts and stops Tomcat server
#
### END INIT INFO

APPL_DIR=/home/vagrant/appl
TOMCAT_DIR=$APPL_DIR/tomcat

case "$1" in
 start)
   su vagrant -c $TOMCAT_DIR/bin/startup.sh
   ;;
 stop)
   su vagrant -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 10
   ;;
 restart)
   su vagrant -c $TOMCAT_DIR/bin/shutdown.sh
   sleep 20
   su vagrant -c $TOMCAT_DIR/bin/startup.sh
   ;;
 *)
   echo "Usage: tomcat {start|stop|restart}" >&2
   exit 3
   ;;
esac
